name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Dependencies
        working-directory: functions
        run: npm install

      - name: Deploy to Firebase
        run: npx firebase-tools deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
